# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Create Pull Request to master
      uses: peter-evans/create-pull-request@v2
      with:
        token: d1817afa1c551c4d61954927f2c8130cb1ec0077
        commit-message: Merge to master
        title: Merge to master
        base: master
        branch: dev
