name: Check labels

on:
  pull_request:
    branches: [ dev ]
    types: [opened, labeled, unlabeled]

jobs:
  statusCheck:
    runs-on: ubuntu-latest
    env:
      required: join(['bug', 'documentation'])
      tags: join(github.event.pull_request.labels.*.name)
    steps:
      - name: check label
        # if: contains(github.event.pull_request.labels.*.name, 'bug') != true &&
        #     contains(github.event.pull_request.labels.*.name, 'documentation') != true
        
        run: |
          python -c "exit( len(set('${{ tags }}'.split(',')) - set(['${{ required }}'])) != 1)"
          if [ $? -eq 1 ]; then
            echo "required one of [${{ tags }}] tag!"
            exit 1
          fi
    
