name: Check labels

on:
  pull_request:
    branches: [ dev ]
    types: [opened, labeled, unlabeled]

jobs:
  statusCheck:
    runs-on: ubuntu-latest
    env:
      required: 'bug,documentation'
      tags: ${{ join(github.event.pull_request.labels.*.name) }}
    steps:
      - name: check label
        run: |
          echo "\033[0;31mrequired one of [${{ env.tags }}] tag!\033[0m"
          python -c "exit( len(set('${{ env.tags }}'.split(',')).intersection(set('${{ env.required }}'.split(',')))) != 1)"
          
          
