name: Check labels

on:
  pull_request:
    branches: [ dev ]
    types: [opened, labeled, unlabeled]

jobs:
  statusCheck:
    runs-on: ubuntu-latest
    steps:
      - name: check label fail
        if: contains(github.event.pull_request.labels.*.name, 'bug') != true &&
            contains(github.event.pull_request.labels.*.name, 'documentation') != true
        run: |
          echo "one or more of bug or documentation tag is required!"
          exit 1
      
