name: Check labels

on:
  pull_request:
    branches: [ dev ]
    types: [opened, labeled, unlabeled]

jobs:
  statusCheck:
    runs-on: ubuntu-latest
    env:
      required: 'bug,documentation'
      tags: ${{ join(github.event.pull_request.labels.*.name) }}
    steps:
      - name: check label
        run: |
          echo "required one of [${{ env.required }}] tag!"
          python -c "exit( len(set('${{ env.tags }}'.split(',')).intersection(set('${{ env.required }}'.split(',')))) != 1)"
      - name: The job has succeeded
        if: success()
        run | curl -H "Authorization: token ${{ secrets.TOKEN }}" \
                 -X POST \
                 -H "Content-Type: application/json" \
                 -d '{"state":"success","description":"passed","context":"CheckLabels"}' \
                 https://api.github.com/repos/paopaojr/backend-changelog-generator/statuses/${{ github.event.pull_request.head.sha }}
              exit 0
      - name: The job has failed
        if: failure()
        run | curl -H "Authorization: token ${{ secrets.TOKEN }}" \
                 -X POST \
                 -H "Content-Type: application/json" \
                 -d '{"state":"failure","description":"need one of bug, documentation","context":"CheckLabels"}' \
                 https://api.github.com/repos/paopaojr/backend-changelog-generator/statuses/${{ github.event.pull_request.head.sha }}
               exit 1
               
