name: Check labels

on:
  push

jobs:
  statusCheck:
    runs-on: ubuntu-latest
    env:
      required: 'bug,documentation'
      tags: ${{ join(github.event.pull_request.labels.*.name) }}
      statusContext: 'CheckLabels'
      requestHeader: 'Authorization: token ${{ secrets.GITHUB_TOKEN }}'
      statusUrl: 'https://api.github.com/repos/paopaojr/backend-changelog-generator/statuses/${{ github.event.pull_request.head.sha }}'
    steps:
      - name: check label
        run: python -c "exit( len(set('${{ env.tags }}'.split(',')).intersection(set('${{ env.required }}'.split(',')))) != 1)"


